DigiLabFoodApp/DigiLabFoodApp/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DigiLabFoodApp.Models
{
    public class Payment
    {
        
        [Required]
        public int PaymentId { get; set; }

        [Required]
        public string OrderReference { get; set; }

        [Required]
        public string PaymentReference { get; set; }

        [Required]
        public Decimal TransactionAmount { get; set; }

        [Required]
        public PaymentStatus PaymentStatus { get; set; }

        public DateTime PaymentDate { get; set; }
        public int CardId { get; set; }

        [ForeignKey("ApplicationUser")]

        public string ApplicationUser_Id { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

    }

    public enum PaymentStatus
    {

        Pending, Paid
    }
}

DigiLabFoodApp/DigiLabFoodApp/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DigiLabFoodApp.Models;
using DigiLabFoodApp.ViewModel;

namespace DigiLabFoodApp.Controllers
{
    [Authorize]
    public class PaymentsController : Controller
    {
        private string  UserId { get; set; }
        private ApplicationDbContext db = new ApplicationDbContext();
        
        

        // GET: Payments
        public ActionResult Index()
        {
            return View(GetPaymentDetails());
        }

        
        public ActionResult Invoice(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(GetOrderItems(id, UserId));
        }
        //[Route("D/{id}")]
        // GET: Payments/Details/5
        public ActionResult Details(int? id)
        {
            ApplicationUser user = db.Users.FirstOrDefault( o=> o.Email == HttpContext.User.Identity.Name);
            //Payment paymentw = new Payment
            //{
            //    ApplicationUser = user,
            //    ApplicationUser_Id = user.Id,
            //    PaymentDate = DateTime.Now,
            //    OrderReference = "DLD",
            //    PaymentReference = "NIWNDWFUWF",
            //    PaymentStatus = PaymentStatus.Paid,
            //    TransactionAmount = 2900M
            //};

            //db.Payments.Add(paymentw);
            //db.SaveChanges();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.FirstOrDefault(o => o.PaymentId == id && o.ApplicationUser_Id == user.Id);

            if (payment == null)
            {
                return HttpNotFound();
            }


            return View(GetOrderItems(id, user.Id));
           
        }

        // GET: Payments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PaymentId,OrderReference,PaymentReference,TransactionAmount,PaymentStatus,CardId")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Payments.Add(payment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(payment);
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PaymentId,OrderReference,PaymentReference,TransactionAmount,PaymentStatus,CardId")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(payment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(payment);
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Payment payment = db.Payments.Find(id);
            if (payment == null)
            {
                return HttpNotFound();
            }
            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Payment payment = db.Payments.Find(id);
            db.Payments.Remove(payment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public List<PaymentHistoryViewModel> GetPaymentDetails()
        {
            List<PaymentHistoryViewModel> result = new List<PaymentHistoryViewModel>();

            ApplicationUser user = db.Users.FirstOrDefault(o => o.Email == HttpContext.User.Identity.Name);
            try
            {
                result = db.Database.SqlQuery<PaymentHistoryViewModel>("exec GetPaymentsForUser @UserId", new SqlParameter("@UserId", user.Id)).ToList();

            }
            catch (Exception ex)
            {


            }
            return result;
        }

        public OrderDetailsPage GetOrderItems(int? id, string userId)
        {
            List<OrderDetailViewModel> result = new List<OrderDetailViewModel>();
            OrderDetailsPage orderDetails = new OrderDetailsPage();

            try
            {
                result = db.Database.SqlQuery<OrderDetailViewModel>("exec GetSingleOrderDetailForUser @UserId, @PaymentId", 
                    new SqlParameter("@UserId", userId),
                    new SqlParameter("@PaymentId", id)
                    ).ToList();
                
                //get total charge after multiplying the unit price and quantity
                Decimal totalCharge = 0.00M;
                foreach (var item in result)
                {
                    totalCharge += item.TotalPrice;
                }
                Decimal chargePerUnit = 0.00M;

                //get total charge before multiplying the unit price and quantity
                foreach (var item in result)
                {
                    chargePerUnit += item.MenuPrice;
                }



                // add a new order of service charge to the list
                OrderDetailViewModel serviceChargeModel = new OrderDetailViewModel
                {
                    ItemNo = result.Count + 1,
                    MenuName = "Service Charge",
                    OrderQuantity = 1,
                    MenuDetail = "Service charge on Order",
                    MenuPrice = Convert.ToDecimal(ConfigurationManager.AppSettings["ServiceCharge"].ToString().Trim()) / 100 * chargePerUnit,
                   
                    TotalPrice = Convert.ToDecimal(ConfigurationManager.AppSettings["ServiceCharge"].ToString().Trim())  / 100 * totalCharge
                };

                result.Add(serviceChargeModel);


                //get the total charge after adding the service charge
                var orderTotalCharge = 0.0m;
                foreach (var item in result)
                {
                    orderTotalCharge += item.TotalPrice;
                }

                //charge 5% charge on the order
                decimal vatOnOrder = orderTotalCharge * Convert.ToDecimal(ConfigurationManager.AppSettings["VAT"].ToString().Trim()) / 100;

                //then this will be the final charge payable for this order 
                Decimal TotalOrderPrice = orderTotalCharge + vatOnOrder;

                orderDetails.OrderDetail = result;
                orderDetails.TotalCharge = TotalOrderPrice;
                orderDetails.VatOnOrder = vatOnOrder;
                orderDetails.OrderTotalCharge = orderTotalCharge;

                var users = db.Users.FirstOrDefault(o => o.Id == userId);

                var userAddress = from user in db.Users
                                   join address in db.Addresses on user.Address.AddressId equals address.AddressId
                                   where user.Id == userId
                                   select new { City = address.City, Street = address.Street, State = address.State, Country = address.Country, HouseNumber = address.HouseNumber  };
                var customerAddress = new Address();

                //fix later
                foreach (var item in userAddress)
                {
                    customerAddress.City = item.City;
                    customerAddress.Country = item.Country;
                    customerAddress.HouseNumber = item.HouseNumber;
                    customerAddress.State = item.State;
                    customerAddress.Street = item.Street;
                }

                orderDetails.BuyerAddress = customerAddress;
            }
            catch (Exception ex)
            {
                //log exception
            }
            return orderDetails;
        }
        //private List<Payment> GetAllPaymentDetail()
        //{

        //}
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DigiLabFoodApp/DigiLabFoodApp/Views/Payments/Create.cshtml
@model DigiLabFoodApp.Models.Payment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrderReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransactionAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PaymentStatus, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PaymentStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DigiLabFoodApp/DigiLabFoodApp/Views/Payments/Delete.cshtml
@model DigiLabFoodApp.Models.Payment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderReference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderReference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentReference)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentReference)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransactionAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaymentStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaymentStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DigiLabFoodApp/DigiLabFoodApp/Views/Payments/Details.cshtml
@model DigiLabFoodApp.ViewModel.OrderDetailsPage

@{
    ViewBag.Title = "Details";
}
<!-- partial -->
<div class="container-fluid page-body-wrapper">
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card px-2">
                        <div class="card-body">
                            <div class="container-fluid">
                                <h3 class="text-right my-5">Invoice&nbsp;&nbsp;#INV-17</h3>
                                <hr>
                            </div>
                            <div class="container-fluid d-flex justify-content-between">
                                <div class="col-lg-3 pl-0">
                                    <p class="mt-5 mb-2"><b>Shop Name</b></p>
                                    <p>
                                        @Html.DisplayFor(model => model.BuyerAddress.HouseNumber), @Html.DisplayFor(model => model.BuyerAddress.Street),
                                        <br>@Html.DisplayFor(model => model.BuyerAddress.City), @Html.DisplayFor(model => model.BuyerAddress.City)<br/>
                                        @Html.DisplayFor(model => model.BuyerAddress.Country)
                                    </p>
                                </div>
                                <div class="col-lg-3 pr-0">
                                    <p class="mt-5 mb-2 text-right"><b>Invoice to</b></p>
                                    <p class="text-right">Customer Name,<br> 40, Awolowo road,<br> Ikoyi, Lagos state.</p>
                                </div>
                            </div>
                            <div class="container-fluid d-flex justify-content-between">
                                <div class="col-lg-3 pl-0">
                                    <p class="mb-0 mt-5">Invoice Date : 4th September 2018</p>
                                    <p>Due Date : 4th September 2019</p>
                                </div>
                            </div>
                            
                                <div class="container-fluid mt-5 d-flex justify-content-center w-100">
                                    <div class="table-responsive w-100">

                                        <table class="table">
                                            <thead>
                                                <tr class="bg-light">
                                                    <th>#</th>
                                                    <th>Menu Name</th>
                                                    <th>Description</th>
                                                    <th class="text-right">Quantity</th>
                                                    <th class="text-right">Unit cost</th>
                                                    <th class="text-right">Total</th>
                                                </tr>
                                            </thead>

                                            <tbody>
                                                  @foreach (var row in Model.OrderDetail)
                                                    {
                                                        <tr class="text-right">
                                                            <td class="text-left">
                                                                @Html.DisplayFor(modelItem => row.ItemNo)
                                                            </td>
                                                            <td class="text-left">
                                                                @Html.DisplayFor(modelItem => row.MenuName)
                                                            </td>
                                                            <td class="text-left">
                                                                @Html.DisplayFor(modelItem => row.MenuDetail)
                                                            </td>
                                                            <td>
                                                                @Html.DisplayFor(modelItem => row.OrderQuantity)
                                                            </td>
                                                            <td>
                                                                &#8358;
                                                                @Html.DisplayFor(modelItem => row.MenuPrice)
                                                            </td>
                                                            <td>
                                                                &#8358;
                                                                @Html.DisplayFor(modelItem => row.TotalPrice)
                                                            </td>
                                                        </tr>
                                                    }



                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                            
                                <div class="container-fluid mt-5 w-100">
                                    <p class="text-right mb-2">Sub - Total amount: &#8358; @Html.DisplayFor(model => model.OrderTotalCharge)</p>
                                    <p class="text-right">vat (10%) : &#8358;@Html.DisplayFor(model => model.VatOnOrder)</p>
                                    <h4 class="text-right mb-5">Total : &#8358;@Html.DisplayFor(model => model.TotalCharge)</h4>
                                    <hr>
                                </div>
                                <div class="container-fluid w-100">
                                    <a href="#" class="btn btn-primary float-right mt-4 ml-2 print" ><i class="mdi mdi-printer mr-1" ></i>Print</a>
                                    <a href="#" class="btn btn-success float-right mt-4"><i class="mdi mdi-telegram mr-1"></i>Send Invoice</a>
                                    
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
</div>
<!-- page-body-wrapper ends -->
  </div>
<!-- container-scroller -->

DigiLabFoodApp/DigiLabFoodApp/Views/Payments/Edit.cshtml
@model DigiLabFoodApp.Models.Payment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PaymentId)

        <div class="form-group">
            @Html.LabelFor(model => model.OrderReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransactionAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaymentStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.PaymentStatus, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PaymentStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DigiLabFoodApp/DigiLabFoodApp/Views/Payments/Index.cshtml
@model IEnumerable<DigiLabFoodApp.ViewModel.PaymentHistoryViewModel>

@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderReference)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentReference)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CardId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderReference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentReference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PaymentId }) |
                @Html.ActionLink("Details", "Details", new { id = item.PaymentId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PaymentId })
            </td>
        </tr>
    }

</table>*@
<!-- partial -->
<div class="container-fluid page-body-wrapper">
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Transaction History</h4>
                            <div class="row">
                                <div class="col-12 table-responsive">
                                    <table id="order-listing" class="table">
                                        <thead>
                                            <tr class="bg-light">
                                                <th>REF #</th>
                                                <th>Order Ref</th>
                                                <th>Payment Date</th>
                                                <th>Subscription Plan</th>
                                                <th>Plan Type</th>
                                                <th>Amount Paid</th>
                                                <th>Status</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@Html.DisplayFor(modelItem => item.PaymentReference)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.OrderReference)</td>
                                                    <td> @Html.DisplayFor(modelItem => item.PaymentDate)</td>
                                                    <td>Breakfast Only</td>
                                                    <td>Month</td>
                                                    <td>&#8358; @Html.DisplayFor(modelItem => item.TransactionAmount)</td>
                                                    <td>
                                                        <label class="badge badge-info">@Html.DisplayFor(modelItem => item.PaymentStatus)</label>
                                                    </td>
                                                    <td class="text-right">
                                                        <a class="btn btn-light" href=@Url.Action("Details", "Payments", new { id = item.PaymentId })>
                                                            <i class="mdi mdi-eye text-primary"></i>View Invoice
                                                        </a>
                                                    </td>
                                                </tr>
                                            }
                                            </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
</div>
<!-- page-body-wrapper ends -->
  </div>